function [ fh ] = bsc_quickEdgeCheck(fg, fgc, figCap)
%
% inputs:
% fg  = fe fiber group of standard structure to be plotted
% fgc = cleaned fe fiber group of standard structure to be plotted
% 
% outputs: 
% fh = a figure handle for the figure object generated by this script

figure('Name', figCap);

% % add Global title to plot
% set(gcf,'NextPlot','add');
% axes;
% h = title(figCap);
% set(gca,'Visible','off');
% set(h,'Visible','on'); 

%% plot original fibers

ax1 = subplot(1, 2, 1);
hold on;

for ii = 1:length(fg.fibers)    
    plot3(fg.fibers{ii}(1,:),fg.fibers{ii}(2,:),fg.fibers{ii}(3,:),'Color',[0 1 0]);
end

title(['Original Fibers: ' num2str(length(fg.fibers))]);
xlabel('X coordinates');
ylabel('Y coordinates');
zlabel('Z coordinates');

%% plot original fibers

ax2 = subplot(1, 2, 2);
hold on;

for ii = 1:length(fgc.fibers)    
    plot3(fgc.fibers{ii}(1,:),fgc.fibers{ii}(2,:),fgc.fibers{ii}(3,:),'Color',[0 0 1]);
end

title(['Cleaned Fibers: ' num2str(length(fgc.fibers))]);
xlabel('X coordinates');
ylabel('Y coordinates');
zlabel('Z coordinates');

%% global plot options

% link the subplot rotations together
Link = linkprop([ ax1, ax2 ], {'CameraUpVector', 'CameraPosition', 'CameraTarget', 'CameraViewAngle'});
setappdata(gcf, 'StoreTheLink', Link);

% lock axes for similar scaling
linkaxes([ ax1, ax2 ], 'xy');

% return figure handle
fh = gcf;

end

